### ISSUE TITLE
Notepad++ 8.3.1 Exception due to GotoLineCol.dll

### ISSUE THREAD

**Issue by sq2500** [shriprem/Goto-Line-Col-NPP-Plugin#19]
Exception Reason: invalid stoi argument

**Comment by shriprem** [comment]
This was triggered due to lack of support for 'windows-latest' (i.e., windows 2022) in CodeQL. See: https://github.com/actions/virtual-environments/issues/4856

Updated codeql-analysis.yml with 'windows-2019' instead of 'windows-latest' to fix this issue.

**Comment by shriprem** [comment]
@sq2500, when you reported this issue back on Feb 17, I wrongly presumed that it was coming from the "CodeQL bot". Sorry!

This confusion happened because your issue had just a single sentence with only 5 words in it; and that same morning the weekly automated CodeQL Analysis Action had failed on both my plugin for reasons I had indicated in my initial response to your issue report.

Since then another plugin user reported this same error. If you are interested, you can view the conversation at #22.

As far as I can currently tell, this error occurred due to the command line parameters processing by the GotoLineCol plugin. Based on that assumption, I have fixed the error in commit "[Handled Utils::StringtoInt exception with non-numeric input](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/commit/6442b6a13b4b2e7030d48cb0eb8f140a92fa85b0)".

If you can still recall the context when you received this error message, please provide it to me for further analysis. Also, has this error occurred again after that day? Thank you!

**Comment by shriprem** [comment]
I was finally able to replicate the "Exception Reason: invalid stoi argument" error message with the **_older 2.2.0.2_** version of the GotoLineCol plugin: by trying to launch Notepad++ with a file whose name either started with '-n' or '-c' as in file names: "-newfile.bat" & "-changefile.txt". 

File extensions didn't matter. Only the file name has to  start with either a '-c' or '-n'. See the sample clip below:

![image](https://user-images.githubusercontent.com/45252729/165885271-658902d9-5719-4f2e-b117-b317559cb2f3.png)

I can also confirm that this error message did not occur when I tried the same files with the [2.2.0.3 special versions](https://github.com/shriprem/Goto-Line-Col-NPP-Plugin/issues/22#issuecomment-1112324114) of the GotoLineCol plugin I had provided earlier yesterday in #22.

If these file name patterns ring a bell, please let me know so that I can put this issue to rest. Thanks!
