### ISSUE TITLE
Add border to window

### ISSUE THREAD

**Issue by gitttt54** [shriprem/Goto-Line-Col-NPP-Plugin#32]
Hi,
this is actually a great an useful plugin! Thank you for developing such a neat tool! I have searched many years for such an ease !

Would you mind to add a border around the window, because it is barely seeable for me.
The white background around that plugins window is the background of npp++  and there is no contrast (I can see).

Thank you again! and a good time!

no border now:
![no](https://user-images.githubusercontent.com/96403800/191938704-b8a4f4da-393d-453f-8942-7e155c71712f.jpg)

with border:
![border](https://user-images.githubusercontent.com/96403800/191938732-674e014f-c25e-4812-9a15-62fc23d8d9ba.jpg)

Now with text in background (which is not always there...):

no border now:
![no](https://user-images.githubusercontent.com/96403800/191939626-d9ecbb30-96c8-4c0d-a4f6-285e5c0a9bd5.jpg)

with border:
![border](https://user-images.githubusercontent.com/96403800/191939619-5f76a4c6-205b-49f6-9158-18cb722ef9e2.jpg)

**Comment by shriprem** [comment]
@gitttt54 , thank you for your feedback. But I am unable to replicate the lack of border issue.

### On multiple Windows 11 PCs
![2022-09-23_124505](https://user-images.githubusercontent.com/45252729/192105493-841b19c3-d132-4ad7-8132-71a2d6200dbe.png)

### On a **Windows 10** PC
![2022-09-23_112010](https://user-images.githubusercontent.com/45252729/192105547-a72aa848-b789-4ad3-b3d9-da5293e8c478.png)

### Probable Causes for your issue
On Windows 7 and Windows 11, floating dock panels have distinct borders and a shadow. On Windows 10, they only have an edge apparent by the shadow around the floating dock panel. But in your screenshots, I don't see that shadow. This could be due to any one of the following:
* You are using a Windows 10 Lite version that has disabled the shadows as an optimization.
* You have purposely disabled the shadows in your Windows.
* Your graphics hardware is incapable of rendering shadows.

### Suggested Solutions (use any one)
1.  **Dock the panel to a side**: The _GotoLineCol_ plugin panel is by default docked to right side within Notepad++. But you can dock the panel to the left (or top or bottom) if you prefer. When the plugin panel is docked to one of the sides, the docking container of Notepad++ will have a thick frame at the edge bordering the edit control.

3.  **Use Notepad++ Darkmode**: You could use one of the darkmode tones available in Notepad++. The plugin panel will then get rendered in a dark color. If you prefer your text background to be in a light color, you could use the Notepad++ menu option: **Settings » Style Configurator... » Select Theme** and choose **Default (stylers.xml)**. This combo will give you dark plugin panels contrasting with text on the default light background.

4. **Set Background color to off-white**: You could set the default background color in Notepad++ to a slightly off-white color. For example, light cream. To do this, use the Notepad++ menu option: **Settings » Style Configurator...**.  Then click on the color patch next to **Background Colour** and then the **More Colours...** button in the pop-down. Then specify a light cream color for the default background. Like so:
![2022-09-23_123303](https://user-images.githubusercontent.com/45252729/192107112-3b708452-c1cf-4fbc-bd67-9003a72ab7b3.png)


If you are not satisfied with any of the offered solutions, let me know. If so, provide me more details on your Windows and Notepad++ versions. You could do this by copying and pasting the text you see when you go to Notepad++ menu **? » Debug Info...**.

**Comment by gitttt54** [comment]
Thank you for your very detailed reply.

I will try all of the suggestions for my npp v8.4.4 (64bit) and windows10 pro 120.2212.4180.0 when I'm back on the computer.

Meanwhile I can send you an image, where the find-dialogue has a border in npp and the plugin has not.
That was odd to me, therefore my posting ;-D

If it is caused by some windows colour settings, it'll fixed quickly, I guess.

Thanks again!

![npp](https://user-images.githubusercontent.com/96403800/192151734-bf0c0154-b21b-4b2f-8d27-7d8574de160d.jpg)

**Comment by shriprem** [comment]
### Clarification
Dialogs in Notepad++ such as _Find/Replace_, _Preferences..._, _Style Configurator..._ are static dialogs. That is, they don't dock as a side panel. In fact, if you click on the **Preferences** button in the _GotoLineCol_ panel, you will see a similar static dialog, with identical edge/border styling in your Windows 10 PC.

Whereas the _GotoLineCol_ panel is a _**Dockable**_ dialog. The panel can dock to any of the 4 sidess or float at any user-adjustable size.

The underlying theme and behavior for both these classes of dialogs are controlled by the Windows OS, and to some extent by Notepad++'s dockable panel container. This was quite evident with the comparison pictures I posted of the same dialog on Windows 10 and Windows 11 PCs.

Trying to override any behavior, such as drawing custom edges/borders could run contrary to the OS theming. And, this would create issues for several thousands of other users of this plugin who seem to have no issue with the current state of the plugin's visual aspects.

### Recommended Solution
I dealt with Windows 10 only briefly. Since I went from Windows 7 to Windows 11 with only a short time in between on Windows 10. So, it took me a while to recall the color customization screen on Windows 10.

For now, ignore the solutions I had suggested in my previous post. And try changing the Color Personalization settings indicated below.

Click on the Windows Start button and just type in "color settings". Click on "Color Settings (System Settings)" in the suggested list that pops up. You should then see a screen similar to the screenshot below.
   OR
Alternatively, you could get to this same screen using keyboard shortcut Windows + X » Settings » Personalization » Colors.

In the _Personalization » Colors_ screen, make sure that boxes for the following settings are checked.
1. Transparency effects » ON
2. Show accent color on the following surfaces » Start, taskbar, and action center
3. Show accent color on the following surfaces » Title bars and window borders

I think that the last checkbox (Title bars and window borders) is the most critical. For further fine tuning, you can experiment switching between _Light_ and _Dark_ under _Windows mode_ and _default app mode_.

For comparison, see the numbered checkboxes in the screenshot below.
![image](https://user-images.githubusercontent.com/45252729/192312579-88d8a80e-5c7a-4314-baac-2901095ce5a2.png)

If this solution (recommended) or the ones in my earlier post resolves your issue, please feel free to close this issue.

**Comment by shriprem** [comment]
One last thing. You may have chosen a gray shade as the accent color. Consider choosing a more vivid shade such as blue, green or red as the accent color.

**Comment by gitttt54** [comment]
You definately have knowledge of those thing! Thank you for the clarification too! 

I have spend an hour clicking, coloring, resizing, moving, etc. without any success. Accent color on/off. Transparent on/off. Darkmode windows on/off. Darkmode npp on/off. Different styles....

No way to get a colored border.
Now I know, that those panels don't have a border at all. 

Panelizing is not an option for me, so
I used solution 3 from you first post (Set Background color to off-white) and now I can recognize the panel a little bit better. Thats ok.
Thank you very much for your (more npp+windows than for your great plugin) help!
